use crate::error::{MiniZensicalError, Result};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const DEFAULT_CONFIG_TOML: &str = r#"# Rustring Configuration
# Generated by `rustring init`.
#
# More options: https://github.com/TZMydl2006/Rustring

[project]
# The name of your site (required, non-empty)
site_name = "My Documentation Site"

# Documentation source directory (default: "docs")
# docs_dir = "docs"

# Build output directory (default: "site")
# site_dir = "site"

# Use directory URLs (default: true)
# use_directory_urls = true

# Optional: site URL for canonical links
# site_url = "https://example.com"
"#;

const DEFAULT_INDEX_MD: &str = r#"---
title: Welcome
order: 1
---

# Welcome to Your Documentation Site

Edit this page at `docs/index.md` and run `rustring serve` to preview.
"#;

/// Initialize a new project with a default `zensical.toml` and `docs/index.md`.
///
/// Existing files are not overwritten.
pub fn init_project(config_path: &Path) -> Result<()> {
    let config_path = absolute_path(config_path)?;
    let root_dir = config_path
        .parent()
        .ok_or_else(|| {
            MiniZensicalError::InvalidConfig(String::from(
                "configuration file must live inside a directory",
            ))
        })?;

    if !config_path.exists() {
        if let Some(parent) = config_path.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| MiniZensicalError::io("create", parent, error))?;
        }
        fs::write(&config_path, DEFAULT_CONFIG_TOML)
            .map_err(|error| MiniZensicalError::io("write", &config_path, error))?;
        println!("Created {}", config_path.display());
    } else {
        println!("Config already exists: {}", config_path.display());
    }

    let docs_dir = root_dir.join("docs");
    let index_md = docs_dir.join("index.md");

    if !docs_dir.exists() {
        fs::create_dir_all(&docs_dir)
            .map_err(|error| MiniZensicalError::io("create", &docs_dir, error))?;
        println!("Created {}", docs_dir.display());
    }

    if !index_md.exists() {
        fs::write(&index_md, DEFAULT_INDEX_MD)
            .map_err(|error| MiniZensicalError::io("write", &index_md, error))?;
        println!("Created {}", index_md.display());
    } else {
        println!("Index page already exists: {}", index_md.display());
    }

    println!(
        "Project initialized in {}",
        root_dir.display()
    );
    println!("Run 'rustring serve' to preview.");
    Ok(())
}

fn absolute_path(path: &Path) -> Result<PathBuf> {
    if path.is_absolute() {
        return Ok(path.to_path_buf());
    }

    let current_dir = env::current_dir()
        .map_err(|error| MiniZensicalError::io("read current directory", ".", error))?;
    Ok(current_dir.join(path))
}
